services:
  db:
    image: postgres:15
    container_name: trading_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always

volumes:
  postgres_data: